apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-fleet
  name: fleet-cd
  namespace: fleet-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-fleet
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-fleet
    spec:
      containers:
      - image: cklitscher/fleet:2941cd1e0dc048e4838c8eef2c4cca48f5af2df3
        imagePullPolicy: Always
        name: container-0
        ports:
        - containerPort: 80
          name: test
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
